buildscript {
    ext {
        kotlin_version = '1.8.22'
        // Downgrade Gradle from 8.1.0 to 8.0.2 for better stability
        gradle_version = '8.0.2'
    }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.android.tools.build:gradle:$gradle_version"
        classpath 'com.google.gms:google-services:4.4.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.10'
    }
}


tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
