// This file was auto-generated by generate-firebase-options.sh
// Do not edit this file manually. Instead, update google-services.json
// and run: bash scripts/generate-firebase-options.sh

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, kReleaseMode, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'kanken-dev',
    authDomain: 'kanken-dev.firebaseapp.com',
    databaseURL: 'https://kanken-dev.firebaseio.com',
    storageBucket: 'kanken-dev.appspot.com',
  );

  /// リリースビルドは本番（ukalab-prod）、それ以外（debug/profile）は開発（ukalab-dev）。
  /// どちらも うかラボ共通プロジェクト。データは exams/kanji_kentei/ 配下。
  /// ※ CI は google-services.json（= ukalab-dev）からこのファイルを再生成する。
  static FirebaseOptions get android => kReleaseMode ? _androidProd : _androidDev;

  static const FirebaseOptions _androidProd = FirebaseOptions(
    apiKey: 'AIzaSyDZdjJ53kTfALpV_ti_ipLpxMeNVhLXOAE',
    appId: '1:264757683394:android:1e007ed51f14dfc79a475b',
    messagingSenderId: '264757683394',
    projectId: 'ukalab-prod',
    storageBucket: 'ukalab-prod.firebasestorage.app',
  );

  static const FirebaseOptions _androidDev = FirebaseOptions(
    apiKey: 'AIzaSyCtYZQVS6ZElOuJwXnYZERNctGeB8G9wuY',
    appId: '1:765180094909:android:f01e93b4172209730e8ad4',
    messagingSenderId: '765180094909',
    projectId: 'ukalab-dev',
    storageBucket: 'ukalab-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'kanken-dev',
    databaseURL: 'https://kanken-dev.firebaseio.com',
    storageBucket: 'kanken-dev.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'kanken-dev',
    databaseURL: 'https://kanken-dev.firebaseio.com',
    storageBucket: 'kanken-dev.appspot.com',
  );
}
