#!/bin/bash

##########################################################
# Firebase Options ジェネレータ
#
# 用途: google-services.json から firebase_options.dart を生成
# 使い方: bash scripts/generate-firebase-options.sh
##########################################################

set -e

# 色定義
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
GOOGLE_SERVICES_JSON="${PROJECT_ROOT}/android/app/google-services.json"
OUTPUT_FILE="${PROJECT_ROOT}/lib/firebase_options.dart"

echo -e "${BLUE}🔥 Firebase Options ジェネレータ${NC}\n"

# Step 1: google-services.json 確認
echo -e "${YELLOW}📖 Step 1: google-services.json を確認${NC}"

if [ ! -f "$GOOGLE_SERVICES_JSON" ]; then
    echo -e "${RED}❌ google-services.json が見つかりません${NC}"
    echo "Expected: $GOOGLE_SERVICES_JSON"
    exit 1
fi

echo -e "${GREEN}✓ google-services.json が見つかりました${NC}\n"

# Step 2: jq でデータを抽出
echo -e "${YELLOW}⚙️  Step 2: Firebase 設定を抽出${NC}"

if ! command -v jq &> /dev/null; then
    echo -e "${RED}❌ jq がインストールされていません${NC}"
    echo "Ubuntu/Debian: sudo apt-get install jq"
    echo "macOS: brew install jq"
    exit 1
fi

# google-services.json から値を抽出
PROJECT_ID=$(jq -r '.project_info.project_id' "$GOOGLE_SERVICES_JSON")
PROJECT_NUMBER=$(jq -r '.project_info.project_number' "$GOOGLE_SERVICES_JSON")
FIREBASE_URL=$(jq -r '.project_info.firebase_url' "$GOOGLE_SERVICES_JSON")
STORAGE_BUCKET=$(jq -r '.project_info.storage_bucket' "$GOOGLE_SERVICES_JSON")
MOBILE_SDK_APP_ID=$(jq -r '.client[0].client_info.mobilesdk_app_id' "$GOOGLE_SERVICES_JSON")
API_KEY=$(jq -r '.client[0].api_key[0].current_key // "YOUR_ANDROID_API_KEY"' "$GOOGLE_SERVICES_JSON")

if [ "$PROJECT_ID" = "null" ] || [ -z "$PROJECT_ID" ]; then
    echo -e "${RED}❌ google-services.json から project_id を取得できません${NC}"
    exit 1
fi

echo -e "${GREEN}✓ 設定を抽出しました${NC}\n"

# 検証
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}📋 抽出されたデータ:${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "  Project ID:        $PROJECT_ID"
echo "  Project Number:    $PROJECT_NUMBER"
echo "  Firebase URL:      $FIREBASE_URL"
echo "  Storage Bucket:    $STORAGE_BUCKET"
echo "  Mobile SDK App ID: $MOBILE_SDK_APP_ID"
echo -e ""

# Step 3: firebase_options.dart を生成
echo -e "${YELLOW}📝 Step 3: firebase_options.dart を生成${NC}\n"

cat > "$OUTPUT_FILE" << 'EOF'
// This file was auto-generated by generate-firebase-options.sh
// Do not edit this file manually. Instead, update google-services.json
// and run: bash scripts/generate-firebase-options.sh

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'PROJECT_ID_PLACEHOLDER',
    authDomain: 'PROJECT_ID_PLACEHOLDER.firebaseapp.com',
    databaseURL: 'DATABASE_URL_PLACEHOLDER',
    storageBucket: 'STORAGE_BUCKET_PLACEHOLDER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API_KEY_PLACEHOLDER',
    appId: 'MOBILE_SDK_APP_ID_PLACEHOLDER',
    messagingSenderId: 'PROJECT_NUMBER_PLACEHOLDER',
    projectId: 'PROJECT_ID_PLACEHOLDER',
    databaseURL: 'DATABASE_URL_PLACEHOLDER',
    storageBucket: 'STORAGE_BUCKET_PLACEHOLDER',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'PROJECT_ID_PLACEHOLDER',
    databaseURL: 'DATABASE_URL_PLACEHOLDER',
    storageBucket: 'STORAGE_BUCKET_PLACEHOLDER',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'PROJECT_ID_PLACEHOLDER',
    databaseURL: 'DATABASE_URL_PLACEHOLDER',
    storageBucket: 'STORAGE_BUCKET_PLACEHOLDER',
  );
}
EOF

# プレースホルダーを実際の値で置換
sed -i "s|PROJECT_ID_PLACEHOLDER|$PROJECT_ID|g" "$OUTPUT_FILE"
sed -i "s|DATABASE_URL_PLACEHOLDER|$FIREBASE_URL|g" "$OUTPUT_FILE"
sed -i "s|STORAGE_BUCKET_PLACEHOLDER|$STORAGE_BUCKET|g" "$OUTPUT_FILE"
sed -i "s|API_KEY_PLACEHOLDER|$API_KEY|g" "$OUTPUT_FILE"
sed -i "s|MOBILE_SDK_APP_ID_PLACEHOLDER|$MOBILE_SDK_APP_ID|g" "$OUTPUT_FILE"
sed -i "s|PROJECT_NUMBER_PLACEHOLDER|$PROJECT_NUMBER|g" "$OUTPUT_FILE"

echo -e "${GREEN}✓ firebase_options.dart を生成しました${NC}"
echo "  出力: $OUTPUT_FILE\n"

# Step 4: ファイルの検証
echo -e "${YELLOW}🔍 Step 4: 生成されたファイルを検証${NC}\n"

if [ -f "$OUTPUT_FILE" ]; then
    FILE_SIZE=$(wc -c < "$OUTPUT_FILE")
    LINE_COUNT=$(wc -l < "$OUTPUT_FILE")

    echo -e "${GREEN}✓ ファイルが生成されました${NC}"
    echo "  サイズ: $FILE_SIZE バイト"
    echo "  行数: $LINE_COUNT 行"

    # プレースホルダー残りチェック
    if grep -q "PLACEHOLDER\|YOUR_" "$OUTPUT_FILE"; then
        echo -e "${YELLOW}⚠️  警告: 置換されていないプレースホルダーがあります${NC}"
        echo "  iOS, macOS, Web用のAPI キーを Firebase Console から取得してください"
    else
        echo -e "${GREEN}✓ すべてのプレースホルダーが置換されました${NC}"
    fi
else
    echo -e "${RED}❌ ファイル生成に失敗しました${NC}"
    exit 1
fi

echo -e "\n"

# Step 5: 確認
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Firebase Options が生成されました!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

echo "次のステップ:"
echo "1. lib/firebase_options.dart を確認"
echo "2. flutter pub get を実行"
echo "3. flutter test でテスト実行"
echo "4. git add lib/firebase_options.dart でコミット"
echo ""

exit 0
